# Generated by Django 4.0 on 2022-11-20 13:29

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default-profile.png', null=True,
                                    upload_to=users.models.Profile.profile_directory_path),
        ),
    ]
