# Generated by Django 4.0 on 2022-11-19 18:09

from django.db import migrations, models
import modules

class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_alter_profile_date_of_birth_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default-profile.png', null=True,
                                    upload_to=modules.users.models.Profile.profile_directory_path),
        ),
    ]
