# Generated by Django 4.0 on 2022-11-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(max_length=512),
        ),
    ]
