# Generated by Django 4.0 on 2022-11-21 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('content', '0006_alter_entry_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='user_id',
        ),
        migrations.AddField(
            model_name='entry',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
