# Generated by Django 4.0 on 2022-11-19 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('comment', '0002_alter_comment_approved_alter_comment_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments',
                                    to='auth.user'),
            preserve_default=False,
        ),
    ]
